-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 09:17:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `Prénom` VARCHAR(45) NULL,
  `Nom` VARCHAR(45) NULL,
  `Numero_telephone` VARCHAR(13) NULL,
  `Email` VARCHAR(60) NULL,
  `Identifiant` VARCHAR(45) NULL,
  `Mot_de_passe` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sonde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sonde` (
  `idSonde` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Inactif` TINYINT NOT NULL,
  PRIMARY KEY (`idSonde`),
  UNIQUE INDEX `idSonde_UNIQUE` (`idSonde` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relevé`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relevé` (
  `idRelevé` INT NOT NULL AUTO_INCREMENT,
  `Température` DOUBLE NULL,
  `Humidité` DOUBLE NULL,
  `Niveau_batterie` DOUBLE NULL,
  `Signal_RSSI` INT NULL,
  `Date_relevé` DATETIME NULL,
  `Sonde_idSonde` INT NOT NULL,
  PRIMARY KEY (`idRelevé`),
  UNIQUE INDEX `idRelevé_UNIQUE` (`idRelevé` ASC) VISIBLE,
  INDEX `fk_Relevé_Sonde1_idx` (`Sonde_idSonde` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alerte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alerte` (
  `idAlerte` INT NOT NULL,
  `Niv` DOUBLE NULL,
  `Operateur` VARCHAR(2) NULL,
  `Type` VARCHAR(45) NULL,
  `Actif` TINYINT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Relevé_idRelevé` INT NOT NULL,
  PRIMARY KEY (`idAlerte`),
  UNIQUE INDEX `idAlerte_UNIQUE` (`idAlerte` ASC) VISIBLE,
  INDEX `fk_Alerte_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Alerte_Relevé1_idx` (`Relevé_idRelevé` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
